### ISSUE TITLE
Implement 'Validate' use-cases step (4)

### ISSUE THREAD

**Issue by dladd** [cellml/libcellml#122]
This issue covers implementation of the Validate step as outlined in the [use-cases doc](http://libcellml.readthedocs.io/en/latest/usecases.html) and based on the requirements from the planning discussion in #118. This currently includes:
- [ ] Create, load, and modify models and then validate them (the test is that the models are correctly identified as valid or invalid, and for the case when they are invalid the correct reason is given, covering each rule in [the specification](https://docs.google.com/document/d/1MleZJF6DYp4FO4vxslAHInrRFMqrSpARa1s_dPhwYU0/edit?usp=sharing)).
- [x] MathML validation to use libxml2 + the [W3C MathML DTD](https://www.w3.org/Math/DTD/Overview.html)

**Comment by dladd** [comment]
The current plan is to use the MathML DTD to validate our math strings. However, Spec 17.8.4-5 (quoted below) requires the introduction of `cellml:units` attributes in `ci` and `cn` elements, which are not part of the standard MathML DTD. I see two possible ways around this:
- **(A)** We add the `cellml:units` attribute to ci/cn elements in the MathML DTD we distribute as part of libCellML.
- **(B)** Since we are only passing the error messages from the DTD-based MathML validation to our own `Validator` error logger, we could filter out the errors associated with these valid (to us) attributes by their message string.

I suppose this is mainly a matter of whether we mind distributing our own modified MathML DTD. I think I am personally in favour of (B) as I'd prefer to keep the MathML DTD standard and modular.

> 17.8. Interpretation of mathematics
> ...
> - 4. The MathML elements requiring additional type information are:
>   - 1. Every MathML cn element
>   - 2. Every ci element that defines a new variable inside an bvar element.
> - 5. Every MathML element requiring additional type information (as defined above) MUST have an attribute information item in the CellML namespace, with local name units. The value of this attribute information item MUST be a valid units reference. The referenced units SHALL NOT affect the mathematical interpretation of the CellML model. However, CellML processing software MAY use this information to assist the user in the detection and correction of units errors in the CellML model.

**Comment by agarny** [comment]
Another option (which I use in OpenCOR; see [here](https://github.com/opencor/opencor/blob/e16b32ecbe8fa363fd38332af8ec8ea862faa553/src/plugins/miscellaneous/Core/src/corecliutils.cpp#L527) and [here](https://github.com/opencor/opencor/blob/e16b32ecbe8fa363fd38332af8ec8ea862faa553/src/plugins/miscellaneous/Core/src/corecliutils.cpp#L495)) is to 'clean up' the math string:
1. Check whether the math string can be loaded (using `libxml2`). If it can, then carry on otherwise consider the math string as not MathML valid.
2. Remove anything from the math string that is not part of the MathML namespace.
3. Validate the 'cleaned up' math string using the MathML DTD.

Step 2 should be really straightforward. Not only that, but it will also ensure that we don't have to worry about adding CellML-specific attributes (or something else) in the future (should we ever decide/need to do that). Finally, to have a 'cleaned up' math string might prove useful in other situations (e.g. to convert Content MathML to Presentation MathML).

**Comment by nickerso** [comment]
Validating the "cleaned" MathML string is an interesting approach, but won't help validate the presence of required units attributes. But is useful to use the standard MathML DTD to validate the math string.

Since we'll need to iterate over the XML tree to get any units for validation anyway, perhaps the validation of the presence of them can be done then instead of as part of the DTD validation.

**Comment by dladd** [comment]
Thanks @agarny and @nickerso. 

Excising the cellml attributes after we validate them **(C)** does sound like a good option. We can parse the tree once as XML without a DTD, do our validation of CellML variables/units and remove `cellml:units` attributes to give us a "clean" MathML string, then parse/validate the clean string using the DTD. (This won't affect the content of the actual math string on the component object.)

I also realise now that (B) probably won't work as a single parse/validate option since it appears libxml doesn't keep the "erroneous" attributes in the resulting tree. So (C) now sounds like the way to go to me.

**Comment by dladd** [comment]
If there are no objections, I'd like to replace our `STANDARD_UNIT_X` string constants (in units.h) with a `Units::StandardUnit::X` enum. This would allow us to efficiently check against our limited set of standard units during validation. Conversion to strings can be done with a map, similar to our treatment of `Prefix`.

This will also require additional overloaded `add/removeUnit()` methods to provide support for `StandardUnit enum` method signatures.
