### ISSUE TITLE
reading for nothing

### ISSUE THREAD

**Issue by HeJunhong1107** [cellml/libcellml#1262]
I have finished the tourial in [User document](https://libcellml-tutorials.readthedocs.io/en/latest/tutorials/tutorial1/index.html), and sucessful reading tutorial1.cellml by python。

But when I try to read the any cellml models，which were downloaded on https://models.physiomeproject.org,  the loaded model was empty. for example：[Weinstein_2000_AE1.zip](https://github.com/user-attachments/files/17469866/Weinstein_2000_AE1.zip)

![image](https://github.com/user-attachments/assets/94235a90-c45e-4479-8c39-daab49aa9da9)

Could you please help me with the weird phenomenon？

**Comment by nickerso** [comment]
most of the CellML models in the repository are going to be CellML 1.0 or 1.1 - you will need to parse them in "non strict" mode for libCellML to be able to load them. For example, in Python, use `parser = Parser(false)`. If you inspect the errors and warnings logged by the parser in your example, you'd find that it likely failed due to the input model not being CellML 2.0. In non strict mode, the parser will try its best to import CellML 1.x models.

**Comment by hsorby** [comment]
The models on PMR are typically version 1.0 CellML models or version 1.1 CellML models.  LibCellML deals with version 2.0 CellML models.  

To work with version 1.0 or  version 1.1 models the parser needs to be in permissive mode, this is done by setting the parser to not be strict when parsing models.

```
parser->setStrict(False)
```

If you end up needing to read a model with imports the importer also needs to be in permissive mode.

**Comment by hsorby** [comment]
Damn it someone was already answering.

**Comment by HeJunhong1107** [comment]
@hsorby
 : ) , Thanks a lot for your kind reply!

**Comment by HeJunhong1107** [comment]
@nickerso 
I got it, thanks a lot~

**Comment by nickerso** [comment]
thanks @HeJunhong1107 - I'll close this issue now but feel free to re-open if needed. I've also added #1265 to help us remember to surface some documentation that will guide libCellML users in using CellML 1.x models.
