### ISSUE TITLE
setImport and getImport.

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#188]
In issue #187 it was mentioned that the getImport and setImport functions and documentation was unclear as to what was going to happen.  Should we make this clearer?

**Comment by hsorby** [comment]
I think it could make sense to use setImportModel and getImportModel perhaps.  This may then lead us to renaming and Import as ImportModel.  There is already a setImportReference and getImportReference.  (This API is from the ImportedEntity class.)

**Comment by hsorby** [comment]
Or we could add more information into the documentation for the methods that explain what is going on better.

**Comment by nickerso** [comment]
Just to clarify in my own mind: `(set|get)Import` is setting or getting the instance of an imported model to use (i.e., an `Import` not a `Model`); `(set|get)ImportReference` is setting a reference to the name of the entity in that instance of an imported model (typically these are both used via the `Component::setSourceComponent()` or `Units::setSourceUnits()` methods).

The need for having a handle to the `Import` is simply to ensure that we are correctly grouping imported components and units with the correct instance of an imported model. `(set|get)Import` makes sense to me as we are dealing with `Import`s, not models per se.

I don't think the current documentation (see [here](http://autotest.bioeng.auckland.ac.nz/libcellml-buildbot/b88e0a16a54ddb76c6dec855971bdb7d371f8e73/dox/code/classlibcellml_1_1ImportedEntity.html#a2f07fa682bbd7965ce76779228c8d47c) for example) is particularly clear in this regard and my preference would be to clarify the documentation rather than changing the method names.

**Comment by MichaelClerx** [comment]
Is this still relevant @hsorby @nickerso ?

**Comment by hsorby** [comment]
I think this has now been resolved with the merge of #248. Feel free to re-open if this understanding is incorrect.
