### ISSUE TITLE
Make python bindings installable

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#206]
Goals (*updated Jan 15th 2019*):
- [x] Make it so that a user can compile the bindings and install the python module on their own system
- [x] Make it so that we can compile 'wheels' for windows, os/x, and linux
- [x] Add all of this to pypi

I think this means Python's setuptools needs to be able to compile libcellml, e.g.

- https://stackoverflow.com/questions/42656388/how-to-put-a-swig-pybind11-c-project-on-pypi
- https://stackoverflow.com/questions/29200348/how-to-install-python-binding-of-a-c-library

Thoughts? @hsorby @metatoaster ?

**Comment by metatoaster** [comment]
Seems like libsbml python bindings has also taken this approach, they now have a separate repository for the bindings and their [setup.py](https://github.com/sbmlteam/python-libsbml/blob/master/setup.py) looks something like this. They also provide binary wheels for all supported major platforms via [pypi](https://pypi.python.org/pypi/python-libsbml). However, they achieved this by including a complete copy of the libsbml and the package simply wraps it, which I think is a rather heavy approach.

Or a separate Python source package that contain the pre-generated bindings that then combine and link to libcellml for the "source" distribution.

With Python moving towards wheels as the standard way to distribute packages, if some other method can produce that artifact there is no reason to make setuptools a hard requirement.

I have no preference with any of the approaches since deployment of PMR builds everything needed from source (through buildout), if they are not already available from the Linux distribution.  Though certainly being able to `pip install libcellml` without having to compile anything will be the ideal choice, if we are asking what users want.

**Comment by hsorby** [comment]
I have always thought that we would have to go down the wheel avenue.  I think it is the best and certainly most convenient route we can offer.  This is obviously not useful for Linux users but we should be able to supply a libcellml package that installs the required binaries on those platforms.

**Comment by MichaelClerx** [comment]
If we're doing wheels and packages for major distros it might be a bit of work though... Wonder if there's a more lightweight way of getting pip to work than duplicating the whole repo etc...

**Comment by metatoaster** [comment]
Wheels are the standard packaging method for distributable Python packages, I didn't say do the same thing for major distros, but only to do so via `pip`. If you are going to have setuptools compile libcellml, getting wheels built is literally part of that solution.

**Comment by MichaelClerx** [comment]
That's right, @hsorby said that! Glad to see wheels and pip stuff overlap though! (Never tried wheels myself)

**Comment by MichaelClerx** [comment]
http://swig.org/Doc1.3/Python.html#Python_nn6

**Comment by hsorby** [comment]
The python bindings are now installable and available on PyPi.  We create bindings for Windows, macOS, and GNU/Linux for Python versions 3.9, 3.8 (and for GNU/Linux only Python version 3.7).

If you have a Python that matches one of these versions run `pip install libcellml` to install libCellML.

We are building these packages whenever a release is made using GitHub actions.
