### ISSUE TITLE
CellML namespace: make sure that a model uses the CellML 2.0 namespace

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#236]
The [tests/resources/sine_approximations.xml](https://github.com/cellml/libcellml/blob/develop/tests/resources/sine_approximations.xml) file currently uses the CellML 1.2 namespace while it ought to use the CellML 2.0 namespace.

On a side note: does the CellML namespace get checked as part of the validation process?

**Comment by hsorby** [comment]
No I don't think it does.

**Comment by agarny** [comment]
No to which part of my comment and why?

**Comment by hsorby** [comment]
You only asked one question, does the validation check the namespace? No I don't think it does.  Probably because I didn't think of checking it, the XML checks to make sure the XML is valid the namespace is just some text, libcellml doesn't confirm whether the namespace is the correct one.  Just need to add a test to show the behaviour that we want and if it doesn't pass make the required changes.

**Comment by agarny** [comment]
Ok, I will look into it.

**Comment by nickerso** [comment]
Closing as per discussion on #237.
