### ISSUE TITLE
Code generation output

### ISSUE THREAD

**Issue by massimiliano-leoni** [cellml/libcellml#257]
I am implementing functionalities to convert a `Model` object with associated MathML string into source code used to solve the differential equations specified in the model.

At the moment of writing the code I wrote converts a model like
```
def model my_model as
    def comp main as
        var t: dimensionless;
        var y: dimensionless {init: 1};
        ode(y, t) = 50{dimensionless}*y+y+y+y+cos(abs(sin(y)))-t*t*t*t/t-1{dimensionless};
    enddef;
enddef;
```
in source code like
```
void initConsts(double* constants, double* rates, double* states)
{
    double& y = *(states + 0);


    y = 1;

}
void computeRates(double voi, double* constants, double* rates, double* states, double* algebraic)
{
    const double t = voi;


    double& y = *(states + 0);


    rates[0] = ((((50 * y) + (y + (y + (y + std::cos(std::abs(std::sin(y))))))) - (t * (t * (t * (t * t))))) - 1);

}
void computeVariables(double voi, double* constants, double* rates, double* states, double* algebraic)
{
}
```

**Comment by agarny** [comment]
FWIW, in your model, ``t`` should not be initialised, and I imagine that there is a typo when it comes to the generated code? I mean, ``y`` is initialised to ``-2`` when your model says it should be initialised to ``1``.

Otherwise:
 - Your model is a bit too simplistic. I mean your ``computeVariables()`` method is empty. It would be good to have a model that contains everything that we think we would like to see in terms of code generation.
 - You might prefer the following to what you currently have:
```
const double &t = voi;
const double &y = states[0];
```
- You might want to have a reference for rates too, maybe we could agree on something like:
```
const double &y = states[0];
const double &_y = rates[0];   // I.e. prepend an underscore to indicate that it's a rate?
```
- I wouldn't use ``std::sin()``, but ``sin()``, i.e. plain C rather than C++.
- For readability, it would be good if the generated code was to remove extraneous parentheses.
- I would have ``double *constants`` and the like rather than ``double* constants``. This is our current practice. (Same goes with ``double &y`` vs. ``double& y``.

**Comment by massimiliano-leoni** [comment]
Yes, those in the model are typos, I will correct them right now.

On the other points

1. `computeVariables()` is empty because I don't yet fully understand what it should do. I'll look for a model that has variables to compute later on.
2. I don't think this makes any difference as the compiler will likely optimize-out all these variables.
3. I could find an alias for rates too, yes.
4. What is the difference?
5. Removing unnecessary parentheses would require the generator to understand that some operations are associative. Again, the compiler will optimize this out and, about readability, is it an actual concern for this piece of code? It doesn't look worth the effort.
6. Ok, I'll follow the current practice.

**Comment by agarny** [comment]
2. What doesn't make any difference?
4. As I said, ``std::sin()`` is C++ while ``sin()`` is plain C (assuming you don't have something like ``using namespace std;`` in your code. My point, though, is that I would generate plain C rather than C++ that looks like C.
5. It may not look worth the effort for this particular model (although I think it still would), but for real models, it will definitely make a difference. However, not something that should be done in the first place, I agree. This can wait (and I am happy to do it at some point -- I like my code to look "good" and "clean").

**Comment by massimiliano-leoni** [comment]
2. I thought your point was to add `const` or `&` to what I actually have. I was saying that none of these specifications will make it to the final binary.
3. Ok so it's only a matter of not seeing `std::` in the code? The function definitions are the same so either way is fine for me, I just thought that the use of C-style functions was deprecated in C++.
4. Agreed!

**Comment by agarny** [comment]
2. I guess you are talking about my suggestion of having ``const double &t = voi;``? If so, I agree, although it's just so that it looks more consistent with what you have done for states.
3. It's a matter of having plain C rather than C++. In other words, although this hasn't been discussed among ourselves, I would expect the initial code generation to be for C code, not C++ code.

**Comment by agarny** [comment]
Closing as it has been replaced by issue #359.
