### ISSUE TITLE
XmlNode isType includes namespace, getType does not

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#274]
I find this confusing. In particular, checks like this:

```
if node->isType("X") {
  // Do what you do with a (CellML) X node
} else if node->getType() == "X" {
  // Do what you do with a non-cellml X node
}
```

Doesn't make sense to me to design the API that way

**Comment by nickerso** [comment]
I agree - this API is confusing me. Although its internal only and won't affect users of libCellML, I can foresee a maintenance headache! Now that #264 is merged we can work on "correcting" the `XmlNode` API.

**Comment by agarny** [comment]
Agreed too. Otherwise, note that `XmlAttribute` would have to be changed too.

Anyway, we already have `XmlNode::isTextNode()` and `XmlNode::isCommentNode()`, so for consistency I would rename `XmlNode::isType()` to `XmlNode::isElementNode()`, leaving the current signatures as they are. As for `XmlNode::getType()`, I would probably rename it to `XmlNode::getNodeName()`.

In fact, we are dealing with a node, so maybe we could/should just drop the `Node` bit, i.e. simply have `XmlNode::isElement()`, `XmlNode::isText()`, `XmlNode::isComment()` and `XmlNode::getName()`?

When it comes to `XmlAttribute`, and to be consistent with `XmlNode`, maybe we should rename `XmlAttribute::isType()` to `XmlAttribute::isAttribute()`, and `XmlAttribute::getType()` to `XmlAttribute::getName()`?

**Comment by MichaelClerx** [comment]
> In fact, we are dealing with a node, so maybe we could/should just drop the Node bit, i.e. simply have XmlNode::isElement(), XmlNode::isText(), XmlNode::isComment() and XmlNode::getName()?
>
> When it comes to XmlAttribute, and to be consistent with XmlNode, maybe we should rename XmlAttribute::isType() to XmlAttribute::isAttribute(), and XmlAttribute::getType() to XmlAttribute::getName()?

Sounds good!
Although maybe `hasName` instead of `isElement` and `isAttribute`?

Hold on, that reintroduces the problem :D

Just `is` ?

**Comment by nickerso** [comment]
I like those suggestions for `XmlNode`. Will need to think a bit more about attributes as the type kind of makes sense in that case...

**Comment by agarny** [comment]
Yes, @MichaelClerx, I don't think we want `XmlNode::hasName()`. However, to simply have `XmlNode::is()` wouldn't break consistency with regards to `XmlNode::isText()` and `XmlNode::isComment()`.

Agreed, @nickerso, `XmlAttribute::isAttribute()` is not great.

Ok, so what about:
- `XmlNode::isElement()`, `XmlNode::isText()`, `XmlNode::isComment()` and `XmlNode::getName()`; and
- `XmlAttribute::isType()` and `XmlAttribute::getName()`?

**Comment by nickerso** [comment]
tested out some Visual Studio refactoring in #275 :)
