### ISSUE TITLE
XML Library

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#32]
I was wondering about the use of an XML library, not required as yet but would probably be helpful once deserialisation comes in to play.  Originally I thought we'll just use libxml2 but maybe tinyxml2 (https://github.com/leethomason/tinyxml2) will be sufficient.  We could include this in the code and carry it around, much simpler than finding dependencies (especially on Windows).

Thoughts?

**Comment by mirams** [comment]
+1 for including a simple XML library in the code (not qualified to comment on which one!)

**Comment by agarny** [comment]
I have never tried tinyxml2, but I am all in favour of trying to make things as simple as possible when it comes to 'dependencies'. So, +1.

**Comment by nickerso** [comment]
I agree that an XML parser will be required once we need to start deserialising XML documents. I have no problem using tinyxml2 as a starting point, but I would expect the lack of support for DTDs and XSL (specifically XPath handling) to become a problem in future. 

The simplicity of tinyxml2 is very appealing, so perhaps worth starting with that and then look for a more full-featured XML parser library when needed.

**Comment by nickerso** [comment]
Just taking a look at the issues for tinyxml2 (triggered by discussion on #45) and there are some in there that seem to indicate that we might want to look at more feature-rich XML parsers. Particularly the lack of a deep clone (requested since 2012) and non-standard, but documented, whitespace handling.

Given the resources we have for libCellML, I don't think it would be a useful spend to add features to tinyxml2, but rather take the plunge and go with a more complete, albeit heavy-weight, dependency. I'd suggest libxml2 until we find we need a native C++ parser.

**Comment by jonc125** [comment]
What we want is called [XML Canonicalization (C14N)](http://www.w3.org/TR/xml-c14n). Looks like libxml2 has support for it.

**Comment by agarny** [comment]
I am also in favour of using a library that can be used without the need to add features to it (unless absolutely necessary), so if all we want and need can be done using `libxml2`, then let's go with it.

**Comment by mtcooling** [comment]
+1

**Comment by mirams** [comment]
+1 from me too.

**Comment by hsorby** [comment]
So libxml2 is the xml library we shall use for the project then.
