### ISSUE TITLE
libcellml concatentates mathml blocks but the spec says otherwise

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#378]
I noticed that parsing/printing/storing mathml blocks is treated differently than other objects (variables, units) in that we concatenate them together and return as a string rather than keeping them distinct.  The spec says that a component can:

> contain one or more specific information item children, each of which MUST be of one of the following types:
> A variable element; or
> A reset element; or
> A math element

In other words, we can have more than one math element, but libcellml is not allowing this.  What do people think about changing the handling of the mathml blocks to be closer to how we handle the other children of components to be in line with the spec? 
This would affect the parser, the component storage, and the printer.

@MichaelClerx  does that also mean it may also then need a name or id for the math block in order to determine which one to call? Or we don't care?

**Comment by MichaelClerx** [comment]
MathML elements aren't called per se, they just add information. So you'd need to treat all of them, if there were multiple. Spec could be clearer on this I agree

**Comment by nickerso** [comment]
i'm not sure what the issue is here? The spec is clear in that a component can have multiple `math` children - this is fine, right?

libCellML is clear in that we only deal with MathML as strings and each component only has one math string - multiple string representations of `math` elements can be concatenated together and still be the equivalent XML tree when parsed.

I'm not seeing any reason why we need to deal with a string representation of each math element as a separate string?

**Comment by kerimoyle** [comment]
Yes, multiple math children is fine wrt to the spec.  If concatenating the math elements doesn't change how they're used when there's more than one then that's fine too.  Because libcellml concatenates them into one string I was confused as to whether only one was allowed or not, and then if more than one were allowed, how they were preserved so that they could be distinguished between later.  Sounds like it's more an issue of me not understanding properly than anything else :) Will close it now.  Thanks all
