### ISSUE TITLE
Can libcellml, for the time being, preserve as much of the document structure as possible?

### ISSUE THREAD

**Issue by MichaelClerx** [cellml/libcellml#379]
If `libcellml` is to be the standard implementation, tools like OpenCOR should be able to use it to open files, not make changes, store the files and end up with the same document.

In addition, it means `libcellml` is the best cellml tool out there for creating error messages

This means things like:
 - Not concatenating MathML elements
 - Storing line numbers and column indices for anything that gets parsed (including parts of equations)

**Comment by agarny** [comment]
> If `libcellml` is to be the standard implementation, tools like OpenCOR should be able to use it to open files, not make changes, store the files and end up with the same document.

I am not sure we will ever be able to do this using libCellML since it doesn't have a one-to-one correspondence with the underling CellML format.

**Comment by MichaelClerx** [comment]
So we're building libcellml and hoping someone else will do it better?

**Comment by MichaelClerx** [comment]
Sorry I don't want to be harsh but I don't understand why we wouldn't build the tool so that it can easily be improved to do these things later. That would certainly be a selling point for me

**Comment by agarny** [comment]
Ok, I guess my question is what do you mean exactly by the same document?

If you were to do what you described above then you will always end up with a CellML file that is equivalent to your original CellML file. It's just that its SHA-1 value (or some other checksum value) might not be the same. To have the "exact" same CellML file might be very difficult. For example, imagine the case where you have extraneous spaces that have been added here and there. I could then see it being somewhat tricky (impossible?) to keep track of them.

**Comment by MichaelClerx** [comment]
IDEs do that all the time though

**Comment by MichaelClerx** [comment]
We should at least keep it in the back of our minds that this should be added some day, so don't close any doors unnecessarily at this stage?

**Comment by agarny** [comment]
I believe we have had that discussion before.

Still, I used to wish for the same as you, but I think we have to accept CellML for what it actually is, i.e. "just" a format for encoding biological models.

It's like with Word, I have just created a new Word document and saved it as `x.docx`. I then closed that document, reopened it and saved it as `y.docx`. I then computed the SHA-1 value of both `x.docx` and `y.docx`, and... they are different. Yet, both files are equivalent and, from an end-user viewpoint, that's what matters, no?

**Comment by MichaelClerx** [comment]
I think you're right about outputs: We decided the output should always be in some (yet to be defined) canonical form.
But we still need to know locations of everything for proper error messages. Libxml can easily preserve whitespace. Word has stopped being an example of good software decades ago...

You can close this ticket if you like, but I think we're making a mistake. I mean, _I_ won't use libcellml if it does weird manipulations while reading a file, or if it can't give useful error messages

**Comment by agarny** [comment]
> But we still need to know locations of everything for proper error messages. Libxml can easily preserve whitespace. Word has stopped being an example of good software decades ago...

I used Word, because I had PowerPoint open at the time. :)

More seriously, I agree with your wish to know the exact location of an error. Indeed, I am hoping to add support for CellML 2.0 in OpenCOR's CellML Text view. So, I would, somehow, like to be able to provide error messages a la COR, i.e. to make it possible for a user to double click on an error message and have OpenCOR "jump" to the exact error location. So, to know the exact location of an error in a CellML file would allow me to do that (by means of mapping).

**Comment by nickerso** [comment]
I think we need to be careful not to restrict the functionality of libCellML in an attempt to support a use case that should not exist in this day and age. No libCellML user should ever be looking at the XML code. Full stop. I would say that if you need to know line numbers in the XML file then you either have malformed XML, in which case the raw error message you get from the XML parser will be the best you can get, or libCellML has failed to be a useful tool. We need libCellML to support CellML models, not their XML serialisation - this is the whole reason why the data model for libCellML does not reflect the XML serialisation. And if we can't get such a library to give sufficiently useful error messages then it has failed as a useful tool. The error "message" includes pointers to the involved objects - how a user interface displays those objects is up the user interface. If we don't really start focusing on developing tools that work with models rather than XML files then we're never going to get to where we need to be.

To have "COR-like" text format for CellML 2.0, it needs to be derived from the data model, not some kind of mapping from the XML serialisation - which makes it trivial to highlight the corresponding areas for any error.

**Comment by agarny** [comment]
> To have "COR-like" text format for CellML 2.0, it needs to be derived from the data model, not some kind of mapping from the XML serialisation - which makes it trivial to highlight the corresponding areas for any error.

Mapping from the XML serialisation is what I did in COR, but if a similar result can be achieved using the data model then I woud be happy with that. (It's just that I am not sure it could be done using libCellML, although I won't know for sure until I actually give it a try.)

**Comment by MichaelClerx** [comment]
> a use case that should not exist in this day and age.

I completely disagree. Treating CellML files in this way they become some kind of magic object that only special tools can deal with. And if they break you can't fix them? The whole point of XML is that you can easily work with it in any number of tools, including text editors etc.

Yes CellML XML files are a serialisation of an underlying CellML idea. But libcellml should be the tool that goes from XML to CellML, surely? The tool that's really good at dealing with serialisation and deserialisation?

**Comment by MichaelClerx** [comment]
Anyway, I'm trying to say this as well:

> I think we need to be careful not to restrict the functionality of libCellML

because I'd like to keep options open for libcellml to be the basis for really excellent CellML <--> XML conversion tools?

**Comment by kerimoyle** [comment]
**Regarding the unchanged models being identical or not**, this is the current behaviour:  
```
a) parse model from xml
b) do nothing to model
c) print model back to xml 
d) re-parse model printed in (c)
e) do nothing to model
f) reprint model 
```
In this situation the xml printed at steps (c) and (f) will be character-for-character identical.  Because of the lack of canonical structure from which the model is read in (a), we can't be sure of any line/character similarity, all we can say is that the semantic meaning will be unchanged.  Unless there was a canonical form agreed upon (and which the xml in (a) would have to adhere to) then there's no way to avoid this.

**Regarding whether or not people "should" be interacting with raw xml:**
I don't really have an opinion  ... I don't think we need to make it more difficult, but I also think that spending a lot of time and energy at making text files identical is a bit short-sighted.  The error messages are enough to find the object of interest without relying on a character-based location of them.  

**Re the maths parsing that this all started from:**
What are the disadvantages/advantages to limiting components to containing only one mathml block?  This gets around all the disagreements re handling that have been mentioned?

**Comment by MichaelClerx** [comment]
Thanks @kerimoyle .
I'll just close this for now then so I don't waste everyone's time!
