### ISSUE TITLE
Practical intention behind interface types is not clear?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#403]
I'm confused (still/again/whatever), but in particular about interfaces and their types.  I'm currently working through the validation of equivalent variables, testing that they're not looking into hidden components, and that the interface type is allowed, but I'm a bit stuck ... 

The way I read 11.10.9 is that:
- connected sibling components must each have public interfaces specified on their variables
- connected parent-child components must have a private interface on the parent and a public one on the child.  Parents know everything about their children but not vv.
- there can be no connections other than sibling or parent-child relationships (?)

Can someone help me understand what the practical purposes are for the different types of interface as specified on the _variable_ ?  Imagine this:

parentComponent (grandparent)
  - componentA (father)
      - variableA (public)
      - componentB (child1)
            - variableB (public)
      - componentC (child2)
            - variableC (public)
  - componentD (auntie)
      - variableD (public)

make a sibling connection B-C 
- therefore only the public interface is available
- should be fine

make a sibling connection A-D
- public interface as above
- should be fine

make a parent-child connection A-B
- so interface is private for A and public for B
- validation of the connection to A should fail as it is specified "public" but needs to be "private"

change variable A to be public_and_private
... meets the criterion for interfaces, but we have variables A, B, C, and D equivalent to one another, even though D cannot be equivalent to either B or C as they are in hidden components?  Or, if we're allowed to do the chaining of D<-A->B, C, then there _does_ still exist a network of variables, not simply a set of them as in the discussion in #350 ?

What's the use case for specifying interface types on both the variables and via the encapsulation structure?  Surely if you don't want a variable to be "seen" by some other component/variables you just don't make them equivalent?  I'm missing the point somewhere ...

**Comment by nickerso** [comment]
I think you are correctly interpreting things, so thats a good start :)

Think of variable interfaces as the component-level interface when you are dealing with what is in *this* model. And then the encapsulation is the interface you need to consider when importing a component into a different model - parent-child relationships are maintained, but sibling relationships are broken. 

Or another way to look at it is that the variable level interface is required so that a model author is able to define an interface for the component (and the component's encapsulated children) whereas the encapsulation hierarchy is how the model author can define that "these pieces don't make sense without these other bits".

Not sure if this is helping at all :)
