### ISSUE TITLE
improve how equivalent variables are handled

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#407]
After understanding better (I hope) how equivalent variables work, I think that the way we interact with them in the code is quite strange.  If they're a set of aliases to a single underlying variable, then we should store them as such.  This means we avoid all the complicated looping/not-looping checks/specs (which don't actually make sense if it's not a network), as well as getting around all the recursive calls to check for unit consistency and reset order validity.   Instead of doing the recursive checking later, I think we should rather update the equivalences as a set when they're created.

Here's my example ...

```
TEST(Validator, fixUpEquivVariables)
{
    libcellml::Validator v;
    libcellml::ModelPtr m = std::make_shared<libcellml::Model>();
    libcellml::ComponentPtr comp1 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr comp2 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr comp3 = std::make_shared<libcellml::Component>();
    libcellml::ComponentPtr comp4 = std::make_shared<libcellml::Component>();

    libcellml::VariablePtr v1 = std::make_shared<libcellml::Variable>();
    libcellml::VariablePtr v2 = std::make_shared<libcellml::Variable>();
    libcellml::VariablePtr v3 = std::make_shared<libcellml::Variable>();
    libcellml::VariablePtr v4 = std::make_shared<libcellml::Variable>();

    m->setName("modelName");
    comp1->setName("component1");
    comp2->setName("component2");
    comp3->setName("component3");
    comp4->setName("component4");

    v1->setName("variable1");
    v2->setName("variable2");
    v3->setName("variable3");
    v4->setName("variable4");

    v1->setUnits("dimensionless");
    v2->setUnits("dimensionless");
    v3->setUnits("dimensionless");
    v4->setUnits("dimensionless");

    v1->setInterfaceType("public");
    v2->setInterfaceType("public");
    v3->setInterfaceType("public");
    v4->setInterfaceType("public");

    comp1->addVariable(v1);
    comp2->addVariable(v2);
    comp3->addVariable(v3);
    comp4->addVariable(v4);

    // No encapsulation, all components can access each other
    m->addComponent(comp1);
    m->addComponent(comp2);
    m->addComponent(comp3);
    m->addComponent(comp3);

    // Making a set of equivalent variables v1, v2, v3, v4
    libcellml::Variable::addEquivalence(v1, v2);
    libcellml::Variable::addEquivalence(v2, v3);  
    libcellml::Variable::addEquivalence(v3, v4);
    libcellml::Variable::addEquivalence(v4, v1);   

    // In reality, all of these variables are equivalent to *three* others ... but ...
    EXPECT_EQ(size_t(3), v1->equivalentVariableCount()); // fails, is 2
    EXPECT_EQ(size_t(3), v2->equivalentVariableCount()); // fails, is 2
    EXPECT_EQ(size_t(3), v3->equivalentVariableCount()); // fails, is 2
    EXPECT_EQ(size_t(3), v4->equivalentVariableCount()); // fails, is 2

    // Now say we want to remove one of these variables from the equivalent set:
    libcellml::Variable::removeEquivalence(v2,v3);
    
    // but this does not behave as we'd expect, they are still equivalent because the other side of the "network" is not updated
    // because the findEquivalentVariable function which is called to remove it only returns one equivalence id, but there are
    // two connections?
    EXPECT_FALSE(v2->hasEquivalentVariable(v3));  // Fails, is true
    
    // Since we're allowing more than one connection (as loops in the variables network *are* permitted) then the way in which we store
    // this info doesn't reflect its use.

}
```

Instead of this I think we should just store the set of connected variables as a whole, and add/remove variables from this list as need be.  The structure of the encapsulation will still hold as the gatekeeper to allow the addition/removal to be valid.  The pros of this approach mean we don't have to have recursive calls to check:
- reset orders
- variable units
- variable equivalences
... and that the functions like add/remove equivalence do what a user would expect them to from their names.  

So ... is there a difference in the *use case* (cf implementation difference) between a directly equivalent variable and just another in the same equivalent set?

**Comment by hsorby** [comment]
So I think you are onto something here but I do believe you should write what you expect in the tests.  Much like you have done above but with further examples (in test form) add it to a code change and make a pull request.  It's easier to play around with these changes if they are part of a pull request.

In essence I agree connected variables should be dealt with as sets.

**Comment by kerimoyle** [comment]
Yep, that's my next step, but I do need to know whether it's important to retain the direct equivalence relationship or not so I can write decent tests?

**Comment by hsorby** [comment]
Well for me it is how people feel about the tests and the expected outcomes that are presented.  As the author you get to lead the way :)

**Comment by kerimoyle** [comment]
Ha ... but as a non-user I don't have a good idea about use cases ... so ... is there ever a use situation where the relationship between directly equivalent variables is fundamentally different from more distant equivalences?  ie - is the **use** relationship (cf **implementation** relationship) between `v1` and `v2` above different from between say `v1` and `v3`?

**Comment by hsorby** [comment]
I don't know, I would think not they have been made equivalent.  This then means to me that they are the same.  Re-reading the spec. again I feel this may be the wrong interpretation but it doesn't matter this is the behaviour of how libCellML behaves.  The CellML specification is just that essentially it specifies how the model should be written to disk as long as we don't mess that up we should be good.

**Comment by kerimoyle** [comment]
OK, thanks.  Will have a go :)

**Comment by nickerso** [comment]
The notion of "direct equivalence" is a temporary hack we had to put in as libCellML does not represent connections themselves, so there is no way to parse and serialise equivalent CellML XML without it. Current libCellML object model necessitated exposing this via the public API but as per discussion on #344 this is deprecated and will be dropped (from the public API) one day.

Other than this, there is no use-case where direct equivalence is relevant.

**Comment by kerimoyle** [comment]
OK ... thanks ... I can't believe how fast I forget I've asked all these questions before!  I think (hope?) I get it now :)

**Comment by nickerso** [comment]
I think that the way these various issues and PRs are heading, we're starting to get a little ahead of ourselves and we risk putting too much effort into solving a relatively minor issue instead of adding more useful functionality to libCellML. A we also risk getting too far from the underlying CellML specification which we are supporting, which will result in more work to ensure that things like IDs on `map_variables` elements can be tracked and reserialised as needed.

We initially went with `Variable::addEquivalence()` to avoid any notion of connections from the CellML XML making it into the libCellML public API. This has since been overloaded confusingly with the distinct idea of direct equivalence being different to a standard equivalence. And I believe that, given the directionless connections we now have, that there is no issue with have variable connection cycles as these are either completely fine or invalid depending on the component encapsulation hierarchy.

So I now believe we are going to be much better off to rename `Variable::addEquivalence(v1, v2)` to be `Variable::connect(v1, v2)` - which better reflects what that method actually does. This does away with the need for "direct equivalence". These connections can then be used in the same way as currently implemented to determine when variables are equivalent, but not connected, and could also form the basis for future high-level API that will collate connected variables into some kind of set that could be leveraged, for example, by something like code generation.

Removing the rule about cycles from the spec and making use of the component encapsulation hierarchy along with this connection information will resolve, I think, any outstanding validation issues. I hope. And we should be submitting feature requests for future high level API that would simplify the libCellML API - but we really need to make sure the core library can meet all our immediate needs first.

**Comment by kerimoyle** [comment]
Thanks Andre @nickerso ... but I still feel like I'm missing something.  

> These connections can then be used in the same way as currently implemented to determine when variables are equivalent, but not connected,  

How can variables be equivalent but not connected?  I'm not clear on the difference?

> So I now believe we are going to be much better off to rename Variable::addEquivalence(v1, v2) to be Variable::connect(v1, v2) - which better reflects what that method actually does.

That's fine - but doesn't help me answer the question?  Or are you saying that this PR shouldn't be happening now except to change the name of the function which is exposed to the users?  
We currently have other public functions which talk about direct equivalence - I'm guessing those should those be renamed as well, but then it's a little more difficult to hide the "direct" part:

`bool Variable::hasDirectEquivalentVariable(const VariablePtr &equivalentVariable) const`

If we're happy (or happy for now) to keep the recursive storage structure (and knockon recursion in validation checks) as is, then I'll close this PR.

**Comment by hsorby** [comment]
@nickerso wants us to not get too abstract with our connections.  That is he feels we want to more closely represent what is in the spec.  I couldn't convince him otherwise.

So now we want to think of variable connections as a network (again?!) (dropping the set idea :( ) but ( and it's a big but) not worry about cycles in the variable network because the component encapsulation/hierarchy does not allow us to make cycles.

We also thought that we could add API to the model `inferInterfaces` that would set the appropriate interfaces on variables for the modeller.

**Comment by hsorby** [comment]
Hopefully now we can see that a `connection` is a direct equivalence (in the old parlance) and that two variables are equivalent if they can be reached over the variable connection network.

**Comment by kerimoyle** [comment]
So cyclical variables are ok, but cyclical variables across cyclical component hierarchies are not.  That's all fine, and checked in the #350 PR :) (I too can be shameless in my self-branch-promotion ...)

And another question - why do we even need interface types?  If they are defined by the structure of the components then why use them at all?

> Hopefully now we can see that a connection is a direct equivalence (in the old parlance) and that two variables are equivalent if they can be reached over the variable connection network.

That makes sense, thanks.

**Comment by hsorby** [comment]
Interface types enable the modeller to take control of what is available for further use and hide variables that may change or don't want as part of the API.

They are not defined by the structure of the components but we can infer a viable value given the structure of the components.
