### ISSUE TITLE
Name or map function for generator modelType enums?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#446]
I'll start by saying I loathe `enum`s ... here's one reason why ... 

I'm writing a basic tutorial on use of the code generation, and I want to show how to return the `modelType()` (this being an `enum` of UNKNOWN, ODE, ALGEBRAIC, etc etc).  I think it's really awkward for the user to have to retrieve the model type, then write a big switch statement to find out about their code.  There have been all kinds of reflection-ish macros defined around the place, but none seems to be very clean either.

Can I propose either:

- return a string from the public-facing `modelType()` rather than the enum.  We can keep the current modelType functionality as `modelTypeEnum()` or something ... or create a new function called `modelTypeAsString()` or whatever
- provide a map from the enum to something more useful to the user, in the same way as we've done for the `Prefix` enums.
- overload the utility `convertToString()` to take `ModelType` enums as argument (not really a fan of this)

Thoughts?  @agarny especially?

**Comment by hsorby** [comment]
You can safely rule out the `convertToString()` function as it is not a publicly accessible function.

I don't see how you get away from having to decide what you have whether you return an `enum` or a `std::string`.

Of the three options I would only consider the second option as that has already been done for the `Prefix` enum.

**Comment by kerimoyle** [comment]
I think that the user should deal with strings rather than enums, so if we made that standard throughout then it's straightforward to know what to return.  

Whatever we use under the hood, we could provide set and get functions which take strings, but pass the related enum to the private functions? eg:

```
// user writes code like this
std::string myStringModelType = generator.modelType(); // returns "ODE" or "algebraic" etc
generator.setProfile("python"); // or perhaps "PYTHON" ... ?
std::string myStringProfileType = generator.profile();  // returns "C" or "python" or "PYTHON" etc

// inside non-public function:
void Generator::setProfile(std::string prof) {
   // switch statement to see which profile is needed and retrieve enum
...
  // call the "old" setProfile function with enum
}
```

**Comment by agarny** [comment]
By user, you mean the user of libCellML? If so, as a future libCellML user, I would rather deal with `enum`s. However, if it can make your life easier, then I would like @hsorby go with your second option.

**Comment by kerimoyle** [comment]
> I would rather deal with enums

... what is it about them that I'm missing?  I just don't see anything beyond super complicated code without any real benefits (in the way that we're using them anyhow)?

**Comment by agarny** [comment]
What do you mean by complicated?

Personally, I like the fact that, with `enum`s, I can handle all possible `enum` values within one `switch` statement. To me, this makes my code cleaner. Also, modern IDEs can easily check whether you missed `enum` values in your `switch` statement while it can't if you are dealing with strings. So, in the end, I find that my code is more robust when I use `enum`s. Finally, there are cases (e.g. error reporting) where it's nice to have `enum`s rather than having a string (as we do in libCellML in fact). Indeed, by having an `enum` value, the consumer can generate the error message in the language that s/he wants rather than being stuck with the language used by the library developers.
