### ISSUE TITLE
Remove make_shared for GeneratorProfiles?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#453]
Now that the `std::make_shared` idiom has been replaced by `create()` for `Variable`, `Component`, `Units`, and `Model` should we also do the same for the `GeneratorProfile`?  We still have:

```
libcellml::GeneratorProfilePtr generatorProfile = std::make_shared<libcellml::GeneratorProfile>();
```

**Comment by hsorby** [comment]
`GeneratorProfile` is a class that is able to do both forms.

**Comment by kerimoyle** [comment]
OK, thanks.  I'll use the `create` form in the tutorials so it's the same as everything else then.  Will close this now.

**Comment by agarny** [comment]
> `GeneratorProfile` is a class that is able to do both forms.

What is the rationale for that?

**Comment by hsorby** [comment]
The `create` method was added to make it consistent with other classes.  The constructor was not made private because it doesn't **have** to be.

**Comment by agarny** [comment]
Ok, then I am lost and don't understand what was the rationale behind adding `create()` in the first place, some classes having their constructor made private while others not, and some classes having a `swap()` method and others not. I am clearly missing something since it looks rather inconsistent to me, and somewhat confusing.

**Comment by hsorby** [comment]
Any class that makes use of `enable_shared_from_this` needs to have a private constructor so we control the creation of objects hence the `create` method.  Classes with private constructors no longer need the swap method as it is irrelevant when using pointers.  All `Entities` are classes that we don't want people to construct so their constructors are made protected.

Any other class that does not require a private constructor has had an added `create` method so all objects can be created in the same manner for consistency.

**Comment by agarny** [comment]
> Any class that makes use of `enable_shared_from_this` needs to have a private constructor so we control the creation of objects hence the `create` method. Classes with private constructors no longer need the swap method as it is irrelevant when using pointers.

Fair enough. However, only `Model`, `Component` and `GeneratorEquation` make use of `enable_shared_from_this`. So, for example, why does `Units` do the same?

Also, things used to "work" fine before, so why was the `create` method needed all of a sudden? I can see that it was first done in commit https://github.com/cellml/libcellml/pull/418/commits/de153a3efaff5a286c2ab772979d66c1aec07f44, but it's not clear to me why (even though it all works fine, hence I eventually approved PR #418).

> All `Entities` are classes that we don't want people to construct so their constructors are made protected.

Is that the reason, for example, we can't construct a `Units` instance? Trying to understand a bit more: why could it be bad (?) to allow someone to construct a `Units`?

> Any other class that does not require a private constructor has had an added `create` method so all objects can be created in the same manner for consistency.

Fair enough, but if we want to be consistent (which I like!) then maybe we should go all the way and, therefore, move the constructor of, for example, `GeneratorProfile` in the private section?

**Comment by hsorby** [comment]
So `Model`, `Component`, `GeneratorEquation`, and soon to be `Variable` all make use of `enable_shared_from_this`.  So all of these classes we need to control the creation of objects hence private constructors and the `create` method.  When the class uses `shared_from_this` the object that is being shared from **must** be a shared object.  If this is not the case undefined behaviour will ensue.  Obviously this must be avoided, one way to avoid this problem is to control the creation of objects and make sure all objects created are shared objects thus the private constructor and `create` method.

All `*Entity` classes are classes we don't want people to construct so we make the constructor protected.

All other classes can be constructed using constructors but classes in the `Entity` hierarchy have had their constructors privatised for no particular reason.  This could be reverted and constructor creation could be re-enabled.  I think I originally made this change because I thought it would be more consistent to have all `Entity` classes only allowed to have a `create` method.

**Comment by agarny** [comment]
> So `Model`, `Component`, `GeneratorEquation`, and soon to be `Variable` all make use of `enable_shared_from_this`. So all of these classes we need to control the creation of objects hence private constructors and the `create` method.

Still doesn't tell me why everything used to (or seemed to) work before while now we need that `create` method.

> All `*Entity` classes are classes we don't want people to construct so we make the constructor protected.

Fair enough.

> All other classes can be constructed using constructors but classes in the `Entity` hierarchy have had their constructors privatised for no particular reason. This could be reverted and constructor creation could be re-enabled. I think I originally made this change because I thought it would be more consistent to have all `Entity` classes only allowed to have a `create` method.

I would really like to see consistency all the way through, i.e. all our classes have their constructor privatised, thus "forcing" people to use `create` to get an instance of any of our classes. This would not only allow for consistency throughout the library, but also prevent "confusion".

**Comment by kerimoyle** [comment]
> I would really like to see consistency all the way through, i.e. all our classes have their constructor privatised, thus "forcing" people to use create to get an instance of any of our classes. This would not only allow for consistency throughout the library, but also prevent "confusion".

I agree - this was my original question :)
