### ISSUE TITLE
Validation for units/components in models

### ISSUE THREAD

**Issue by awickens** [cellml/libcellml#480]
Currently, since the addition of the `equivalent()` and `dimensionallyEquivalent()` methods into `libcellml`, there is no associated validation checks in `validator.cpp`. This would mean adding some unit tests and model checks which use `equivalent()` and `dimensionallyEquivalent()`, done in #465.

**Comment by agarny** [comment]
@awickens: it would help if you could reference where that work on `equivalent()` and `dimensionallyEquivalent()` was done. Right now, we know because it was completed yesterday, but... in the future it would be good if we could easily go back to it without having to waste time searching for it.

**Comment by kerimoyle** [comment]
They weren't included in the validator because we're allowed (apparently) to have non-matching multipliers between equivalent variables as long as the base units are the same.  It's waiting for the Issue class (or similar) to be written so that we can return different levels of warning (see https://github.com/cellml/libcellml/pull/368 for discussions)
