### ISSUE TITLE
Should the importer instantiate all objects in an imported model, or just what it needs?

### ISSUE THREAD

**Issue by kerimoyle** [cellml/libcellml#645]
At present, an imported item triggers the import of the entirety of its parent model.  Should it?  See [here](https://github.com/cellml/libcellml/pull/608/files/7349c363d5cef96be92913b41aa037cd7fcdf474#r448045188).

**Comment by kerimoyle** [comment]
It should only import what it needs, so circular siblings are ignored.

**Comment by kerimoyle** [comment]
When we discussed this the other day, @nickerso  said that we should only import the parts of the model which are needed, rather than the entire thing.  That means that this test will change as we won't import the circular dependence. 

```
TEST(Importer, warningUnrequiredCircularDependencyComponent)
{
    // This test is intended to show what happens when one model attempts to import a concrete component from a
    // second model, where the second model has unrelated circular dependencies:
    //   - model1 imports component1 from model2
    //   - model2 defines component1
    //   - model2 also defines a circular dependency unrelated to component1

    // This behaviour will change now - importer should not import things it doesn't need.

    std::string warningMessage = "Cyclic dependencies were found when attempting to resolve components in model 'circularImport3'. The dependency loop is:\n"
                                 "    component 'c' imports 'i_am_ok_but_my_sibling_is_cyclic' from 'circularImport_1.cellml',\n"
                                 "    component 'i_am_cyclic' imports 'c2' from 'circularImport_2.cellml',\n"
                                 "    component 'c2' imports 'c3' from 'circularImport_3.cellml',\n"
                                 "    component 'c3' imports 'i_am_cyclic' from 'circularImport_1.cellml',\n"
                                 "    component 'i_am_cyclic' imports 'c2' from 'circularImport_2.cellml'.";

    auto parser = libcellml::Parser::create();
    auto importer = libcellml::Importer::create();
    auto model = parser->parseModel(fileContents("resolveimports/master1.cellml"));
    EXPECT_EQ(size_t(0), parser->issueCount());
    importer->resolveImports(model, resourcePath("resolveimports/"));
    EXPECT_FALSE(model->hasUnresolvedImports());
    EXPECT_EQ(size_t(1), importer->issueCount());
    EXPECT_EQ(size_t(1), importer->warningCount());
    EXPECT_EQ(warningMessage, importer->warning(0)->description());
}
```






So.  My questions are:
- Since we now have the `Importer` class which saves import dependencies, would you expect a pruned model (ie: a model containing just the component/units that were needed) to be saved to the importer, or the whole thing? 
- If another import needs something different from that same model, would you expect a second instance of a pruned model?

eg:
`modelA` imports `someComponent` from `modelB` -> importer creates `prunedModel1` containing only `someComponent` (and units it needs)
`modelA` imports `someOtherComponent` from `modelB` -> importer creates `prunedModel2` containing only `someOtherComponent` (and units it needs) OR importer adds `someOtherComponent` to existing `prunedModel1`

**Comment by agarny** [comment]
I haven't checked the `Importer` class in details, so I may be getting it completely wrong, but am I to understand that you are suggesting that the `Importer` class keeps / would keep track of `pruneModel1` and `pruneModel2`, or only `pruneModel1` and then update its contents as a result of the second import?

If so, I think either approach is wrong. What I would expect the `Importer` class to do is return an instance of whatever I am interested in. If an import is not tracked by the `Importer` then I would expect it to track it, so that if another model needs that exact same import then the importer will return a cloned copy of it, or something like that.

So, going back to your example:
 - **`modelA` wants to import `someComponent` from `modelB`:** the importer doesn't know about `someComponent` from `modelB`, so it's going to do what it needs to keep track of it and return a cloned copy of it to `modelA`.
 - **`modelA` wants to import `someOtherComponent` from `modelB`:** same story, the importer doesn't know about `someOtherComponent` from `modelB`, so it's going to do what it needs to keep track of it and return a cloned copy of it to `modelA`.

Now, say that:
 - **`modelA` wants to import `someComponent` from `modelB` a second time:** the importer already knows about that import, so it will simply return a cloned copy of it to `modelA`.
 - **`modelC` wants to import `someOtherComponent` from `modelB`:** again, the importer already knows about that import, so it will simply return a cloned copy of it to `modelB`.
 - **`modelC` wants to import `yetAnotherComponent` from `modelB`:** the importer doesn't know about `yetAnotherComponent` from `modelB`, so it's going to do what it needs to keep track of it and return a cloned copy of it to `modelC`.

That's basically how I would expect the `Importer` class to work.

**Comment by kerimoyle** [comment]
So basically inside the `Importer`, we need to have a different kind of instantiation, which is on a component-by-component/units-by-units basis.  The model stored in the `Importer` will be the whole model, but only the required parts of it will be resolved (if they themselves are imports too).  If that's true, then I'd want to return a weak pointer to the model rather than a cloned copy.  Otherwise, we will have different versions of the imported model being referenced depending on what other models had been resolved after it?

**Comment by agarny** [comment]
> So basically inside the `Importer`, we need to have a different kind of instantiation, which is on a component-by-component/units-by-units basis. The model stored in the `Importer` will be the whole model, but only the required parts of it will be resolved (if they themselves are imports too).

That's how I would indeed see the `Importer` class to work.

> If that's true, then I'd want to return a weak pointer to the model rather than a cloned copy. Otherwise, we will have different versions of the imported model being referenced depending on what other models had been resolved after it?

Do we need that referencing? I mean, once `modelA` has got an instance of `someComponent` from `modelB`, why would it need a reference back to the importer? For me, the `Importer` is here to help fully instantiate a model, no? If so, once `modelA` is fully instantiated, I don't see a need to be able to reference back to the importer, or am I missing something? Not only that, but a user may then decide to change the fully instantiated version of `modelA`, so to have a weak pointer to the `someComponent` wouldn't work. (Just thinking out loud, so I might very well be missing something here!)
