### ISSUE TITLE
Use of issue labels

### ISSUE THREAD

**Issue by nickerso** [cellml/libcellml#74]
To date we have not used the GitHub issue labels feature in this project. It would be useful to see whether people think this is something we should start doing? And if we do, we should probably add our intended interpretation for the labels to the [contributing](http://libcellml.readthedocs.org/en/latest/dev_contribution.html) docs.

**Comment by dladd** [comment]
I think I am in favour of them assuming they are as easy to set up as they appear at a glance. It would just make it easier when scanning through the issue list to see if something is a bug, feature, or planning/discussion item.

**Comment by dladd** [comment]
@nickerso just pointed out that only Admins are currently allowed to set issue labels, which is worth keeping in mind. Nothing stops issue authors from suggesting a label in the text of the issue but it does put more work on the Admins.

**Comment by hsorby** [comment]
I thought only admins could create labels, but users could apply already created ones.

**Comment by hsorby** [comment]
My view is that the labels are useful and can be used to categorise issues and pull requests.  They do need to be well thought out though.  When the project gets bigger labels will help with the development.

**Comment by nickerso** [comment]
It seems that users need to have write access to the repository in order to be able to add, edit, remove labels from issues and pull requests.

**Comment by hsorby** [comment]
That's a shame.

**Comment by agarny** [comment]
I was also hoping that a user could assign one or several labels when creating an issue (but not afterwards, to avoid conflicts between users and admins). Hmm, that might then explain why people never assign labels when creating an issue for OpenCOR... :)

Anyway, +1 for using labels. (FWIW, [here](http://opencor.ws/developer/develop/) are the labels used in OpenCOR.)

**Comment by dladd** [comment]
I put in a support query to GitHub support regarding this and they said that it was indeed a deliberate choice. They found that opening up issue labels to the public can lead to an arms race ending in every minor bug being flagged as super-high-priority, must-fix-now.

**Comment by dladd** [comment]
It sounds like there is consensus in favour of using labels- so that just leaves deciding what we want them to be. Unfortunately, I don't have access to the current list of labels as a non-admin. @agarny shared the following currently used for OpenCOR:
- Version
  - Feature
  - Improvement
  - Bug
- Development
  - Task
  - Regression
- Platform
  - Windows
  - Linux
  - OSX

I think the Version and Platform sublabels  are equally applicable to libCellML (as well as Development once we get to releases). I also think we could add a "Discussion" or "Proposal" label in Version to indicate a planning-stage issue for community feedback to guide future development (for example #82 or #65 ). Other classes of issue labels we might consider are 
- Priority
  - High
  - Normal
  - Low
- Status
  - Confirmed
  - Deferred
  - Rejected
  - In-progress
  - Feedback-needed

Once we are happy with the list, I'll update the documentation and leave it to the admins to start using labels on running issues. Which sounds like a good reason to try to clear some outstanding issues :-)

**Comment by agarny** [comment]
I am not sure what the Priority and Status flags would bring besides more 'work'. When it comes to Priority flags, personally I 'replace' them by taking advantage of milestones. For example, in OpenCOR, we have the `0.5` and `0.6` milestones (keeping in mind that the official version of OpenCOR is 0.4.1). So, anything that is 'urgent' is put in the `0.5` milestone (unless it's really critical, in which case I would create a `0.4.2` milestone, etc.). If it is 'normal', I would put it in the `0.6` milestone, and if it's low, I would just leave it without any milestone for the time being. From there, the idea is just to go through all the issues that are in the `0.5` milestone. (It happens that I move issues from one milestone to another, but it's rare.)

As for the Status flags, I feel it's redundant with what can already be done:
- **Confirmed:** a comment acknowledging the issue and a label/milestone/assignee assigned to the issue.
- **Deferred:** put the issue in a 'late' milestone (together with a label and assignee) or simply a message to say that it will be done at some point in the future.
- **Rejected:** a comment and close the issue.
- **In-progress:** commit code to the issue.
- **Feedback-needed:** a message asking for feedback.

At the end of the day, I am in favour of making things as simple as possible otherwise people won't bother labelling things 'properly'.

**Comment by dladd** [comment]
Fair enough- I see how having too many labels could make things more confusing and defeat the purpose.  I suppose my suggestion of a Proposal/Discussion label could similarly be described as Feature/Improvement to reflect the anticipated result. 

So should we go with the same set of labels as OpenCOR?

**Comment by nickerso** [comment]
> At the end of the day, I am in favour of making things as simple as possible otherwise people won't bother labelling things 'properly'.

given only us admins can do anything with labels, it is completely up to us how we use them properly :) As far as I can see, they are really about making it easy for us, as project admins, to be able to list out issues/pull requests that require specific action or have specific features.

I'm not sure I see a need for some of the finer distinctions made in OpenCOR's list. I suggest the following are the collections of issues that I would like to see:
- Bug - something in existing code got broke.
- Feature - a request for a new feature
- Needs test - bug report, contributed code, comment, etc. needs a test to be added to be complete
- Needs docs - as for test, but for documentation
- Needs review - issue/pull request requires more review.

and then the main platforms to label anything that is specific to the given platform. Using milestones as @agarny suggests also makes sense to me.

**Comment by agarny** [comment]
@nickerso's list seems like a good starting point to me. (I would probably just rephrase the labels a bit: `Needs tests`, `Needs documentation` and `Needs reviewing`.)
