### ISSUE TITLE
Analyser/Generator: cache variable equivalences

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#762]
To determine whether two variables are equivalent takes longer using CellML 2.0 than CellML 1.0/1.1 since directionality at the connection level has been dropped in the former. This is clearly a big bottle neck since both the analyser and the generator need to do a lot of those checks.

So, ideally, our `AnalyserModel` class could be used to retrieve whether two variables are equivalent (rather than use the `isSameOrEquivalentVariable()` utility) and cache the results as we go along.

**Comment by nickerso** [comment]
I'm not sure how directionality can impact performance in this case, as equivalence doesn't matter about the direction. But indeed, in the CellML API one of the services would create that static (cached) map of equivalences to enable faster lookup on unchangable models.

**Comment by kerimoyle** [comment]
The other way to do it is to make better use of the adding equivalence function so that it updates a global list, rather than simply the local one.  This way every part of the libcellml functionality can take advantage, not only the generator and analyser?

**Comment by agarny** [comment]
> I'm not sure how directionality can impact performance in this case, as equivalence doesn't matter about the direction.

Indeed! I guess I am too fixed on CellML 2.0 and its lack of directionality at the connection level. :)

> The other way to do it is to make better use of the adding equivalence function so that it updates a global list, rather than simply the local one. This way every part of the libcellml functionality can take advantage, not only the generator and analyser?

That would indeed be a better approach. However, my concern is that it might take "time" to update such a list if you add/remove equivalences? This is why I did at the analyser level since, at that stage, we have a "fixed" model.

**Comment by kerimoyle** [comment]
It would take time, but it would be time taken only once.  And since each time it was done, you eliminate the need for recursion (since you've already got all the equivalent variables in the first layer) it would be pretty negligible?  We could treat it the same way that we do `ImportSource` items: ie, child of the model (though not in a CellML sense), two way updates, K.I.S.S.

A structure like this would work?

```
EquivalentVariableSet
- mVariables -> vector of weak pointers to variables

Variable
- equivalenceSet -> pointer to EquivalentVariableSet item which it sits inside
```


Then each time you add an equivalence you simply merge the equivalence set pointed to by the two variables given.  Tests for equivalence need no recursion, so they're all fast, and we can make the "true" variables available to the user for debugging really easily.

**Comment by agarny** [comment]
I have started work on this, but... say that we add an equivalence between `v1` and `v2`, `v2` and `v3`, and `v3` and `v4`. This means that, for instance, `v1` is equivalent to `v2`, `v3` and `v4`. It is easy to keep track of those equivalences in `v1`. Those equivalences should probably be tracked using weak pointers.

This means that if we remove `v3` using `Component::removeVariable()` then the equivalent variables information held by `v2` and `v4` (in `mEquivalentVariables`) is out of date and will only be updated when we, for instance, call `Variable::equivalentVariableCount()` (since it makes a call to `cleanExpiredVariables()`). However, for some reasons, `Variable::equivalentVariable()` will keep working on an out of date version of `mEquivalentVariables`.

Then, when it comes to tracking direct and indirect equivalences for `v1`, we should somehow update the whole set of equivalent variables. To (somehow) remove `v3` from the set of equivalent variables wouldn't be enough here. We would also need to remove `v4`.

So, yes, I feel like our current handling of (direct) equivalent variables is not ideal and to handle indirect equivalent variables on top of it will make things even more complicated...

**Comment by kerimoyle** [comment]
> It is easy to keep track of those equivalences in v1. 

Not quite what I meant ... I think that all of the variables should store a link to a set between all of the variables.  We prioritise storage of a few more pointers over recursion time.  For example: 

```
v1 is equivalent to v2
v3 is equivalent to v4
v5 is lonely
```
At present, we have two lists, but two pointers to each of them:
```
set1 = [v1, v2]
set2 = [v3, v4]
v1->equivalentList = set1 = v2->equivalentSet
v3->equivalentList = set2 = v4->equivalentSet
v5->equivalenceList = none
```

Adding an equivalence merges the sets of the two variables given:
```
make v5 equivalent to v1:
    merge the lists pointed to by the equivalenceSet of v1 and v5
    update the member pointers

create set3 = [v1, v2, v5]
v5->equivalenceList = set3 = v1->eL = v2->eL


Make v2 equivalent to v4:
     merge the lists pointed to by v2->eL and v4->eL
     update the member pointers

create set4 = [v1, v2, v3, v4, v5]
update all variables to point to set5
```

Removing an equivalence means separating it from the set.  We've already had the discussion around what this means when an "indirect" equivalence remains ... and it's complicated and not really intuitive ... so I suggest we make it easier for everyone.  How about instead of thinking of it as "removing an equivalence" (which doesn't really make sense), think of it as dissociating a single variable from its set.  This way, all of the hidden stuff about indirect connections is avoided, and the user knows which of the variables still has equivalent values.  

~Remove equivalence between v5 and v3~ Remove v3 from its equivalence set
```
mySet = v3->eL
mySet->remove(v3)
v3->eL = none
```

Iterating through equivalent variables is really easy now ... just loop through the variable's equivalence list.  Removing variables from components etc is easy too since it just stores a list of weak pointers: if the variable instance no longer exists, it's automagically removed from the equivalence list anyway.

The user can also see quickly where the connections are, just by iterating through one non-recursive list.
