### ISSUE TITLE
Validator: mention the name of an attribute using single quotes

### ISSUE THREAD

**Issue by agarny** [cellml/libcellml#854]
We should use single quotes around an attribute name that is mentioned in an error message:
 - "name attribute" ---> "'name' attribute";
 - "xlink:href attribute" ---> "'xlink:href' attribute";
 - "component_ref attribute" ---> "'component_ref' attribute";
 - "units_ref attribute" ---" 'units_ref' attribute";
 - "units attribute" ---> "'units' attribute";
 - "interface attribute" ---> "'interface' attribute"; and
 - "cellml:units attribute" ---> "'cellml:units' attribute".

(See [here](https://github.com/cellml/libcellml/pull/837#discussion_r621660820) for some background.)

**Comment by nickerso** [comment]
why? to me, at least for the quoted example, the 'quoted' bit is distinguishing what is the incorrect text in the model whereas the rest of the string is describing what is wrong.

Might be better to see if we can define a "style guide" for error messages and then make sure that libCellML is consistent with that otherwise we'll end up with a series of ad-hoc changes as everyone changes things to match their own preferred style.

**Comment by agarny** [comment]
> why? to me, at least for the quoted example, the 'quoted' bit is distinguishing what is the incorrect text in the model whereas the rest of the string is describing what is wrong.

I was merely pointing out some inconsistencies and suggested what I thought looked better to me at the time.

> Might be better to see if we can define a "style guide" for error messages and then make sure that libCellML is consistent with that otherwise we'll end up with a series of ad-hoc changes as everyone changes things to match their own preferred style.

Agreed, this is probably the best way forward.

**Comment by hsorby** [comment]
https://docs.google.com/document/d/13G-SkuZj0DIm4z8PR7INzi2EFPFWwofgq8FEs2cceVo/edit#
(May not be available to all)

**Comment by agarny** [comment]
Closing this issue and will create any issue that is needed to address our "style guide" for error messages.
