### ISSUE TITLE
How can models with imports be validated?

### ISSUE THREAD

**Issue by jonrkarr** [cellml/libcellml#870]
The validator finds no errors with the following example even though the imported file doesn't exist.

```xml
<?xml version="1.0"?>
<model xmlns="http://www.cellml.org/cellml/2.0#" xmlns:cellml="http://www.cellml.org/cellml/2.0#" xmlns:xlink="http://www.w3.org/1999/xlink" name="level2_model">
    <component name="level2_component">
        <variable name="time" units="dimensionless" interface="public"/>
        <variable name="parameter" units="dimensionless" interface="public"/>
        <variable name="cosine" units="dimensionless" interface="public" initial_value="0"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply><eq/>
                <apply><diff/>
                    <bvar><ci>time</ci></bvar>
                    <ci>cosine</ci>
                </apply>
                <apply><sin/>
                    <apply><times/>
                        <ci>parameter</ci>
                        <ci>time</ci>
                    </apply>
                </apply>
            </apply>
        </math>
    </component>
    <component name="isnt_imported"/>
    <import xlink:href="this_file_should_not_exist..._ever!.xml">
        <component name="also_never_imported" component_ref="not_sure_what_to_look_for"/>
    </import>
</model>
```

Here's how I'm used the validator:
```python
import libcellml
parser = libcellml.Parser()
with open('version2.xml', 'r') as file:
    model = parser.parseModel(file.read())
assert parser.errorCount() == 0
validator = libcellml.Validator()
validator.validateModel(model)
validator.errorCount() == 0
```

How can models with imports be validated?

**Comment by agarny** [comment]
Hi Jonathan,

This is the expected behaviour. libCellML's validator will validate your model against the specifications, i.e. it will tell you whether your CellML file is valid CellML or not. Nothing more nothing less. Once your model is considered valid, you will want, in your case, to flatten it and check whether the flattening resulted in errors (after all your previous steps):

importer = libcellml.Importer()
importer.flattenModel(model)
assert importer.errorCount() == 1
importer.error(0).description()

That last line should output:

"Component 'also_never_imported' requires a model imported from 'this_file_should_not_exist..._ever!.xml' which is not available in the importer."

HTH, Alan.
________________________________
From: Jonathan Karr ***@***.***>
Sent: 09 June 2021 5:28 AM
To: cellml/libcellml ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cellml/libcellml] How can models with imports be validated? (#870)


The validator finds no errors with the following example even though the imported file doesn't exist.

<?xml version="1.0"?>
<model xmlns="http://www.cellml.org/cellml/2.0#<http://www.cellml.org/cellml/2.0#>" xmlns:cellml="http://www.cellml.org/cellml/2.0#<http://www.cellml.org/cellml/2.0#>" xmlns:xlink="http://www.w3.org/1999/xlink<http://www.w3.org/1999/xlink>" name="level2_model">
    <component name="level2_component">
        <variable name="time" units="dimensionless" interface="public"/>
        <variable name="parameter" units="dimensionless" interface="public"/>
        <variable name="cosine" units="dimensionless" interface="public" initial_value="0"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML<http://www.w3.org/1998/Math/MathML>">
            <apply><eq/>
                <apply><diff/>
                    <bvar><ci>time</ci></bvar>
                    <ci>cosine</ci>
                </apply>
                <apply><sin/>
                    <apply><times/>
                        <ci>parameter</ci>
                        <ci>time</ci>
                    </apply>
                </apply>
            </apply>
        </math>
    </component>
    <component name="isnt_imported"/>
    <import xlink:href="this_file_should_not_exist..._ever!.xml">
        <component name="also_never_imported" component_ref="not_sure_what_to_look_for"/>
    </import>
</model>

Here's how I'm used the validator:

import libcellml
parser = libcellml.Parser()
with open('version2.xml', 'r') as file:
    model = parser.parseModel(file.read())
assert parser.errorCount() == 0
validator = libcellml.Validator()
validator.validateModel(model)
validator.errorCount() == 0

How can models with imports be validated?

**Comment by agarny** [comment]
This is the expected behaviour. libCellML's validator will validate your model against the specifications, i.e. it will tell you whether your CellML file is valid CellML or not. Nothing more nothing less. Once your model is considered valid, you will want, in your case, to flatten it and check whether the flattening resulted in errors (after all your previous steps):

```python
importer = libcellml.Importer()
importer.flattenModel(model)
assert importer.errorCount() == 1
importer.error(0).description()
```

That last line should output:

```python
"Component 'also_never_imported' requires a model imported from 'this_file_should_not_exist..._ever!.xml' which is not available in the importer."
```

**Comment by jonrkarr** [comment]
Perfect. The flatten step is exactly what I was looking for.

**Comment by nickerso** [comment]
Perhaps to be clear, if you want to validate the full model you need to resolve imports (which is where the issue with non-existing import sources will be identified) and then validate the resolved model to determine if everything that is needed is now present and valid.

```
# Create an Importer to resolve
i = libcellml.Importer()
# base_dir should be the folder containing the CellML model file that you are trying to resolve
result = i.resolveImports(m, base_dir)
if result != True:
    print('The import resolution issue count is: ', i.issueCount())
    for index in range(i.issueCount()):
        print(i.issue(index).description())

# Create a validator instance v and pass the model to it
v=libcellml.Validator()
# Validate the model m
v.validateModel(m)
```

But also worth noting that the capability of libCellML to resolve imports is limited to local files only. So imports using absolute URLs (e.g., https://models.physiomeproject.org/...) won't resolve.

**Comment by jonrkarr** [comment]
Good to know. Our intention is to use this with COMBINE archives. For this purpose, we'd like to encourage all files to be local (i.e. contained in the archive).

**Comment by agarny** [comment]
Have to give it to @nickerso. His steps describe the correct way to validate a model with imports. My bad!

**Comment by jonrkarr** [comment]
Thanks. I found that the `base_dir` has to include a trailing slash.

**Comment by agarny** [comment]
> Thanks. I found that the `base_dir` has to include a trailing slash.

Indeed, I got bitten by this too. @hsorby and @nickerso, we ought to allow `base_dir` not to have a trailing slash.

**Comment by nickerso** [comment]
> Our intention is to use this with COMBINE archives

Yep, and that is pretty much our rationale for only supporting local files. (Our PMR workspaces are pretty much the same as an extracted archive file.)

The trailing `/` is part of #592 I believe...
