### ISSUE TITLE
Make removeAllIssues in Logger protected

### ISSUE THREAD

**Issue by hsorby** [cellml/libcellml#877]
Should we make the removeAllIssues method protected in the Logger class.  Importer flattenModel is one place where it isn't called unlike parseModel, and validateModel.

**Comment by agarny** [comment]
Are you suggesting to remove `removeAllIssues()` from the `Logger` API? If so, why? Wouldn't you expect people to want to remove all the issues of a logger before doing something that may log (new) issues? I can't recall for certain, but maybe we don't need `removeAllIssues()` anymore since we always ensure that a logger is "empty" before potentially adding (new) issues to it?

If `removeAllIssues()` is to be removed from the `Logger` API, then I wouldn't make it `protected` but move it to the private implementation.

**Comment by hsorby** [comment]
That is essentially my point just about everywhere we remove all issues before performing some action.  So, should we make sure all the loggers remove all issues before and make remove all issues private.  Protected or private implementation same same.  Protected if we don't have a private implementation, private implementation if we do.  Seeing as we can't add an issue externally, we can only interrogate, taking away remove all from the public API seems like something that is on the table.

**Comment by agarny** [comment]
I am definitely happy with removing all issues before starting an action that may generate (new) issues. (After all, this is what I wanted in the first place. :))

Regarding `protected` vs. private implementation. I would go with the latter every time (and create a private implementation if needed), to ensure consistency throughout our API.
